name: Build

on:
  pull_request:
  push:
  release:
    types: [published,prereleased]
    
jobs:
    build:
      name: Build
      env:
        BASE_VERSION: 2.9.99

      runs-on: windows-2019
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build
        run: msbuild /r /t:Build /p:Configuration=Release .\ZXing.Net.Mobile.sln
      - name: Package NuGets
        run: |
          git clone https://github.com/nblockchain/fsx
          $pkgVer = `.\fsx\Tools\fsi.bat fsx\Tools\nugetPush.fsx --output-version $env:BASE_VERSION`

          New-Item -ItemType Directory -Force -Path .\artifacts
          msbuild /t:Pack /p:Configuration=Release /p:PackageOutputPath=..\artifacts /p:PackageVersion=$pkgVer /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg .\ZXing.Net.Mobile\ZXing.Net.Mobile.csproj
          msbuild /t:Pack /p:Configuration=Release /p:PackageOutputPath=..\artifacts /p:PackageVersion=$pkgVer /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg .\ZXing.Net.Mobile.Forms\ZXing.Net.Mobile.Forms.csproj
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: NuGet
          path: .\artifacts

    publish-nuget:
      name: Publish NuGet Packages
      needs: build
      runs-on: windows-2019
      if: github.ref == 'refs/heads/master' && (github.event_name == 'push')
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v1
          with:
            name: NuGet
        - name: Push to GitHub Packages
          run: |
            nuget sources add -Name "GPR" -Source "https://nuget.pkg.github.com/Redth/index.json" -UserName Redth -Password ${{ secrets.GITHUB_TOKEN }}
            nuget setApiKey ${{ secrets.NUGET_API_KEY }} --source "GPR" --skip-duplicate
            nuget push NuGet\*.nupkg -Source "GPR"
        - name: Push to NuGet.org
          run: |
            git clone https://github.com/nblockchain/fsx
            .\fsx\Tools\fsi.bat fsx\Tools\nugetPush.fsx ${{secrets.NUGET_API_KEY}}

